# Generated by Django 5.2.12 on 2026-03-17 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='leave_name',
        ),
    ]
