# Generated by Django 5.2.12 on 2026-03-17 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_remove_leave_leave_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_role',
            field=models.CharField(choices=[('STAFF', 'Staff'), ('MANAGER', 'Manager'), ('HR', 'Human Resources')], default='STAFF', max_length=20),
        ),
    ]
